#!/usr/bin/env bash
# configure web-02 to be identical to web-01 

sudo apt-get update -y -qq
sudo apt-get install nginx -y
# starting nginx service
sudo service nginx start
# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html

sudo sed -i '/server_name _;/a \        error_page 404 /error.html;\n\tlocation = /error.html {\n               root /var/www/html;\n           internal;\n     }'  /etc/nginx/sites-enabled/default
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

#shellcheck disable=SC2154

sudo sed -i "/server_name _;/a \        add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo service nginx restart
