#!/usr/bin/env bash
# This Bash script automates the process of fixing the issue preventing the Nginx installation from listening on port 80 within an Ubuntu container.
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
