#!/usr/bin/env bash
# this script that displays numbers from 1 to 100.
#	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5

for nbr in {0..100};
do
	if (( nbr % 3 == 0 && nbr % 5 == 0 ));
	then
		echo "FizzBuzz"
	elif (( nbr % 3 == 0 ));
	then
		echo "Fizz"
	elif (( nbr % 5 == 0 ));
	then
		echo "Buzz"
	else
		echo "$nbr"
	fi
done
